### ISSUE TITLE
Замечания по 1.3

### ISSUE THREAD

**Issue by sergey-shambir** [dlxgit/TP#3]
- checkedPages должен быть словарём, а не списком. Кроме исправления следует объяснить тут в комментарии, почему. Hint: http://bigocheatsheet.com/
- нет никакого экранирования символов имени, взятого из заголовка страницы (из <titile>). А что, если там будет обратный слеш, процент или ещё какой-то недопустимый для имени папки символ?

**Comment by dlxgit** [comment]
Исправлено.
В среднем словарь эффективнее списка если требуется проверить наличие элемента (временная сложность выполнения меньше), при этом он так же эффективно добавляет новый элемент.

**Comment by sergey-shambir** [comment]
Принято
